root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp\\server.exe ."
bin = "tmp\\server.exe"
full_bin = "tmp\\server.exe"
delay = 1000
kill_signal = "SIGINT"
kill_timeout = 5000

[log]
time = true

[watch]
include_ext = ["go", "json", "html", "css", "js"]
exclude_dir = [".git", "tmp", "node_modules"]
exclude_regex = ["_test.go"]
